
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Scott
 */


public class DoctorView extends javax.swing.JFrame {
    
    private String loginName="NOACCOUNT";
    private String loginPassword="NOPASSWORD";
    
    
    
    private ArrayList<UserInfo> myPatients=new ArrayList<UserInfo>();
    private ArrayList<UserInfo> allPatients=new ArrayList<UserInfo>();
    
    private ArrayList<UserInfo> myNurses=new ArrayList<UserInfo>();
    private ArrayList<UserInfo> allNurses=new ArrayList<UserInfo>();
    
    private ArrayList<UserInfo> patientView=new ArrayList<UserInfo>();
    private ArrayList<UserInfo> nurseView=new ArrayList<UserInfo>();
    
    // TEST CONSTRUCTOR ONLY: actual constructor with account name and password should be called.
    public DoctorView() {
        initComponents();
        //Populate with mock data
        SignedInAsNotifier.setText("TEST MODE ONLY");
        String[] s_allPatientsFirst={"Michael","Dan","Robert","Shawn","Olga","Eileen","Joan"};
        String[] s_allPatientsLast={"Cook","McDonald","Seavey","Boehm","Adkins","Barkley","Pangburn"};
        String[] s_allPatientsUser={"mcook","ddonald","rseavey","sboehm","olgirl203","ebarkley","jpang"};
        
        String[] s_allNursesFirst={"Joy","Amanda","Argentina","Tiesha","Vivian","Gina","Elaine"};
        String[] s_allNursesLast={"Kopec","Davis","Benitez","Wheaton","Hess","Sickler","Glenn"};
        String[] s_allNursesUser={"jkepec","adavis","abenitez","twheat","vhess","ginasick2923","eglenn"};
        for (int i=0;i<s_allPatientsFirst.length;i++)
        {
            UserInfo patient=new UserInfo(s_allPatientsFirst[i],s_allPatientsLast[i],s_allPatientsUser[i]);
            UserInfo nurse=new UserInfo(s_allNursesFirst[i],s_allNursesLast[i],s_allNursesUser[i]);
            allPatients.add(patient);
            allNurses.add(nurse);
            if(i<4)
            {
                myPatients.add(patient);
                myNurses.add(nurse);
            }
        }
        Collections.sort((List)myPatients);
        Collections.sort((List)allPatients);
        Collections.sort((List)myNurses);
        Collections.sort((List)allNurses);
        
        UpdateNurseScrollList();
        UpdatePatientScrollList();
     }
    
    
    
    
    public DoctorView(String accountName, String accountPassword)
    {
        this.initComponents();
        this.loginName=accountName;
        this.loginPassword=accountPassword;
        this.SignedInAsNotifier.setText("Signed in as: "+accountName);
        //Attempt to retrieve information from database
        try{
            ResultSet rs;
            //Get all nurses
            rs = new NurseDB("").getFromAllAccounts("username, firstname, lastname, doctor");
            Utilities.helperStoreUserData(rs,this.allNurses,this.myNurses,accountName);
            
            //Get all patients
            rs = new PatientDB("").getFromAllAccounts("username, firstname, lastname, doctor");
            Utilities.helperStoreUserData(rs,this.allPatients,this.myPatients,accountName);
            
            Collections.sort((List)this.myPatients);
            Collections.sort((List)this.allPatients);
            Collections.sort((List)this.myNurses);
            Collections.sort((List)this.allNurses);
            
            UpdateNurseScrollList();
            UpdatePatientScrollList();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to establish SQL connection. Please check your network settings.\nDetails: "+e.getMessage());
            java.awt.EventQueue.invokeLater(new Utilities.RunnableFrameDisposer(this));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutButton = new javax.swing.JButton();
        SignedInAsNotifier = new javax.swing.JLabel();
        ActionsPane = new javax.swing.JTabbedPane();
        PatientPane = new javax.swing.JPanel();
        PatientScrollList = new javax.swing.JScrollPane();
        PatientList = new javax.swing.JList();
        ViewInfoButton = new javax.swing.JButton();
        PatientCategorySelector = new javax.swing.JComboBox();
        PatientSearchField = new javax.swing.JTextField();
        NursePane = new javax.swing.JPanel();
        NurseScrollList = new javax.swing.JScrollPane();
        NurseList = new javax.swing.JList();
        NurseSearchField = new javax.swing.JTextField();
        NurseCategorySelector = new javax.swing.JComboBox();
        NurseAddButton = new javax.swing.JButton();
        NurseDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        SignedInAsNotifier.setText("Signed in as: ");

        PatientList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Adam Jones", "Michael Stevens", "Kenneth Shive", "Edward Pearsall", "Richard Conti", "John Cephas", "Justin Cook", "Stephen Brand", "Richard Garcia", "Patrick Collard", "Cecil Cortez", "Kevin Appel", "Eugenio Zimmerman", "Roy Kapoor", "Richard Swensen", "Gregory Dawson", "Joseph Sasso", "Richard Pfister", "Robert Wood", "Miles Kelly", "Shaun Lovell", "Paul Gonzales", "Patrick Lacayo", "Martin Price", "Steven Fisher", "Rick Daugherty" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        PatientScrollList.setViewportView(PatientList);

        ViewInfoButton.setText("View Patient Info");
        ViewInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInfoButtonActionPerformed(evt);
            }
        });

        PatientCategorySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "My Patients", "All Patients" }));
        PatientCategorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientCategorySelectorActionPerformed(evt);
            }
        });

        PatientSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PatientSearchFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PatientPaneLayout = new javax.swing.GroupLayout(PatientPane);
        PatientPane.setLayout(PatientPaneLayout);
        PatientPaneLayout.setHorizontalGroup(
            PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPaneLayout.createSequentialGroup()
                .addGroup(PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientPaneLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(PatientCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPaneLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PatientSearchField)
                            .addComponent(PatientScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewInfoButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PatientPaneLayout.setVerticalGroup(
            PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PatientSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientPaneLayout.createSequentialGroup()
                        .addComponent(PatientScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatientCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ActionsPane.addTab("Patient", PatientPane);

        NurseList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Patricia Flanagan", "Margaret Swinney", "Shonta Claudio", "Elizabeth Allard", "Ila Miller", "Patricia Laramie", "Helen Anderson", "Gertie Ramsey", "Jane Thompson", "Alisha Wood", "Jennifer Oberg", "Allison Bunch", "Louis Leech", "Frances Uribe", "Mae Allen", "Clara Ruel", "Dinah Lucius", "Leslie Holgate", "Christine Mims", "Carrie Jackson", "Martha Winnett", "Berniece Cracraft", "Debra Murray", "Dorothy Moore", "Mildred Beach" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        NurseScrollList.setViewportView(NurseList);

        NurseSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NurseSearchFieldKeyTyped(evt);
            }
        });

        NurseCategorySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "My Nurses", "All Nurses" }));
        NurseCategorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseCategorySelectorActionPerformed(evt);
            }
        });

        NurseAddButton.setText("Add New Nurse");
        NurseAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseAddButtonActionPerformed(evt);
            }
        });

        NurseDeleteButton.setText("Delete Nurse");
        NurseDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NursePaneLayout = new javax.swing.GroupLayout(NursePane);
        NursePane.setLayout(NursePaneLayout);
        NursePaneLayout.setHorizontalGroup(
            NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NursePaneLayout.createSequentialGroup()
                .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NursePaneLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(NurseCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NursePaneLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NurseSearchField)
                            .addComponent(NurseScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NurseAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(NurseDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        NursePaneLayout.setVerticalGroup(
            NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NursePaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(NurseSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NurseScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NursePaneLayout.createSequentialGroup()
                        .addComponent(NurseAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NurseDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NurseCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ActionsPane.addTab("Nurse", NursePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignedInAsNotifier)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton))
            .addComponent(ActionsPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignedInAsNotifier))
                .addGap(18, 18, 18)
                .addComponent(ActionsPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void UpdateNurseScrollList()
    {
        Utilities.updateGenericPersonnelListing(NurseCategorySelector,NurseList,NurseSearchField,allNurses,myNurses,nurseView);
    }
    
    private void UpdatePatientScrollList()
    {
       Utilities.updateGenericPersonnelListing(PatientCategorySelector,PatientList,PatientSearchField,allPatients,myPatients,patientView);
    }
    
    private void NurseAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseAddButtonActionPerformed

        new NurseRegister(loginName,loginPassword,this).setVisible(true);
    }//GEN-LAST:event_NurseAddButtonActionPerformed

    public void NurseAddedByRegisterForm(UserInfo nurse)
    {
        allNurses.add(nurse);
        myNurses.add(nurse);
        Collections.sort((List)this.myNurses);
        Collections.sort((List)this.allNurses);
        UpdateNurseScrollList();
    }
    private void NurseDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseDeleteButtonActionPerformed
        int i=NurseList.getSelectedIndex();
        if (i==-1) 
        {
            JOptionPane.showMessageDialog(this, "Please first select a nurse to delete.");
            return;
        }
        
        UserInfo nurse=nurseView.get(i);
        int confirm=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the account "+
              nurse.username+" belonging to " + nurse.firstname + " " + nurse.lastname +  "?");
        if (confirm==JOptionPane.YES_OPTION){
                myNurses.remove(nurse);
                allNurses.remove(nurse);
                NurseDB ndb = new NurseDB(nurse.username);
                try
                {
                    if (ndb.accountExists())
                    {
                        ndb.deleteUser();
                        UpdateNurseScrollList();
                        JOptionPane.showMessageDialog(this, "Successfully deleted "+nurse.username+".");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Could not delete "+nurse.username+" because the user has already been deleted.");
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(this, "Could not delete "+nurse.username+" due to network problems.\nDetails: "+e.getMessage());
                }
            }
    }//GEN-LAST:event_NurseDeleteButtonActionPerformed

    private void ViewInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInfoButtonActionPerformed
        // TODO add your handling code here:
        new PatientPanel_DoctorView(loginName,loginPassword,patientView.get(PatientList.getSelectedIndex()).username).setVisible(true);
    }//GEN-LAST:event_ViewInfoButtonActionPerformed
  
    //Because Swing does not provide for event ordering and problems occur if the event is
    //not processed by Swing before it is processed by this class, invokeLater is used to only
    //update the scrollable after all events are processed in the following four methods.
    
    private void NurseCategorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseCategorySelectorActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdateNurseScrollList();
            }});
    }//GEN-LAST:event_NurseCategorySelectorActionPerformed

    private void PatientCategorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientCategorySelectorActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdatePatientScrollList();
            }});
    }//GEN-LAST:event_PatientCategorySelectorActionPerformed

    private void NurseSearchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NurseSearchFieldKeyTyped
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdateNurseScrollList();
            }});
    }//GEN-LAST:event_NurseSearchFieldKeyTyped

    private void PatientSearchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientSearchFieldKeyTyped

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdatePatientScrollList();
            }});
    }//GEN-LAST:event_PatientSearchFieldKeyTyped

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed

        this.dispose();
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DoctorView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ActionsPane;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton NurseAddButton;
    private javax.swing.JComboBox NurseCategorySelector;
    private javax.swing.JButton NurseDeleteButton;
    private javax.swing.JList NurseList;
    private javax.swing.JPanel NursePane;
    private javax.swing.JScrollPane NurseScrollList;
    private javax.swing.JTextField NurseSearchField;
    private javax.swing.JComboBox PatientCategorySelector;
    private javax.swing.JList PatientList;
    private javax.swing.JPanel PatientPane;
    private javax.swing.JScrollPane PatientScrollList;
    private javax.swing.JTextField PatientSearchField;
    private javax.swing.JLabel SignedInAsNotifier;
    private javax.swing.JButton ViewInfoButton;
    // End of variables declaration//GEN-END:variables
}
