
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Scott
 */
public class DoctorView extends javax.swing.JFrame {
    
    private String loginName="NOACCOUNT";
    private String loginPassword="NOPASSWORD";
    private Connection con=null;
    private HashMap<String,String> nurseNameMapping;
    private HashMap<String,String> patientNameMapping;
    private class UserInfo {
        public String firstname; public String lastname; public String username; 
        public UserInfo(String f, String l, String u){firstname=f;lastname=l;username=u;}
    }
    private List<UserInfo> myPatients;
    private List<UserInfo> allPatients;
    private List<UserInfo> myNurses;
    private List<UserInfo> allNurses;
    
    /**
     * Creates new form DoctorView
     */
    public DoctorView() {
        initComponents();
    }
    public DoctorView(String accountName, String accountPassword)
    {
        this(); //Delegate constructor
        loginName=accountName;
        loginPassword=accountPassword;
        SignedInAsNotifier.setText("Signed in as: "+accountName);
        //Attempt to retrieve information from database
        final String HOST = "jdbc:derby://localhost:1527/information";
        String uName = "healthworks";
        String password = "healthworks";
        try{
            con = DriverManager.getConnection(HOST,uName,password);
            PreparedStatement prep = con.prepareStatement("SELECT username, firstname, lastname, doctor FROM NURSES");
            prep.setString(1,accountName);
            ResultSet rs = prep.executeQuery();
            while(rs.next())
            {
                UserInfo nurse=new UserInfo(rs.getString("firstname"),rs.getString("lastname"),rs.getString("username"));
                allNurses.add(nurse);
                if (rs.getString("doctor").equals(accountName))
                {
                   myNurses.add(nurse);   
                }
                nurseNameMapping.put(nurse.firstname+" "+nurse.lastname,nurse.username);
            }
            //Get all patients
            prep=con.prepareStatement("SELECT username, firstname, lastname, doctor FROM Patients");
            rs=prep.executeQuery();
            while(rs.next())
            {
                UserInfo patient=new UserInfo(rs.getString("firstname"),rs.getString("lastname"),rs.getString("username"));
                allPatients.add(patient);
                if (rs.getString("doctor").equals(accountName))
                {
                   myPatients.add(patient);   
                }
                patientNameMapping.put(patient.firstname+" "+patient.lastname,patient.username);
            }
        }
        catch(SQLException e)
        {
        JOptionPane.showMessageDialog(this,"Unable to establish SQL connection. Please check your network settings.\nDetails: "+e.getMessage());
        this.dispose();
        return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutButton = new javax.swing.JButton();
        SignedInAsNotifier = new javax.swing.JLabel();
        ActionsPane = new javax.swing.JTabbedPane();
        PatientPane = new javax.swing.JPanel();
        PatientScrollList = new javax.swing.JScrollPane();
        PatientList = new javax.swing.JList();
        ViewInfoButton = new javax.swing.JButton();
        PatientCategorySelector = new javax.swing.JComboBox();
        PatientSearchField = new javax.swing.JTextField();
        NursePane = new javax.swing.JPanel();
        NurseScrollList = new javax.swing.JScrollPane();
        NurseList = new javax.swing.JList();
        NurseSearchField = new javax.swing.JTextField();
        NurseCategorySelector = new javax.swing.JComboBox();
        NurseAddButton = new javax.swing.JButton();
        NurseDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoutButton.setText("Logout");

        SignedInAsNotifier.setText("Signed in as: ");

        PatientList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Adam Jones", "Michael Stevens", "Kenneth Shive", "Edward Pearsall", "Richard Conti", "John Cephas", "Justin Cook", "Stephen Brand", "Richard Garcia", "Patrick Collard", "Cecil Cortez", "Kevin Appel", "Eugenio Zimmerman", "Roy Kapoor", "Richard Swensen", "Gregory Dawson", "Joseph Sasso", "Richard Pfister", "Robert Wood", "Miles Kelly", "Shaun Lovell", "Paul Gonzales", "Patrick Lacayo", "Martin Price", "Steven Fisher", "Rick Daugherty" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        PatientScrollList.setViewportView(PatientList);

        ViewInfoButton.setText("View Patient Info");
        ViewInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInfoButtonActionPerformed(evt);
            }
        });

        PatientCategorySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "My Patients", "All Patients" }));
        PatientCategorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientCategorySelectorActionPerformed(evt);
            }
        });

        PatientSearchField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                PatientSearchFieldInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout PatientPaneLayout = new javax.swing.GroupLayout(PatientPane);
        PatientPane.setLayout(PatientPaneLayout);
        PatientPaneLayout.setHorizontalGroup(
            PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPaneLayout.createSequentialGroup()
                .addGroup(PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientPaneLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(PatientCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientPaneLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PatientSearchField)
                            .addComponent(PatientScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewInfoButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PatientPaneLayout.setVerticalGroup(
            PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PatientSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientPaneLayout.createSequentialGroup()
                        .addComponent(PatientScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatientCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ActionsPane.addTab("Patient", PatientPane);

        NurseList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Patricia Flanagan", "Margaret Swinney", "Shonta Claudio", "Elizabeth Allard", "Ila Miller", "Patricia Laramie", "Helen Anderson", "Gertie Ramsey", "Jane Thompson", "Alisha Wood", "Jennifer Oberg", "Allison Bunch", "Louis Leech", "Frances Uribe", "Mae Allen", "Clara Ruel", "Dinah Lucius", "Leslie Holgate", "Christine Mims", "Carrie Jackson", "Martha Winnett", "Berniece Cracraft", "Debra Murray", "Dorothy Moore", "Mildred Beach" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        NurseScrollList.setViewportView(NurseList);

        NurseCategorySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "My Nurses", "All Nurses" }));
        NurseCategorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseCategorySelectorActionPerformed(evt);
            }
        });

        NurseAddButton.setText("Add New Nurse");
        NurseAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseAddButtonActionPerformed(evt);
            }
        });

        NurseDeleteButton.setText("Delete Nurse");
        NurseDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NursePaneLayout = new javax.swing.GroupLayout(NursePane);
        NursePane.setLayout(NursePaneLayout);
        NursePaneLayout.setHorizontalGroup(
            NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NursePaneLayout.createSequentialGroup()
                .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NursePaneLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(NurseCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NursePaneLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NurseSearchField)
                            .addComponent(NurseScrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NurseAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(NurseDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        NursePaneLayout.setVerticalGroup(
            NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NursePaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(NurseSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NursePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NurseScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NursePaneLayout.createSequentialGroup()
                        .addComponent(NurseAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NurseDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NurseCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ActionsPane.addTab("Nurse", NursePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignedInAsNotifier)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton))
            .addComponent(ActionsPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignedInAsNotifier))
                .addGap(18, 18, 18)
                .addComponent(ActionsPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NurseAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseAddButtonActionPerformed

        new NurseRegister(loginName,loginPassword).setVisible(true);
    }//GEN-LAST:event_NurseAddButtonActionPerformed

    private void NurseDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseDeleteButtonActionPerformed
        String nurseName=(String)NurseList.getSelectedValue();
        if (nurseName!=null)
        {
            int confirm=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete "+nurseName+" from your list of nurses?");
            if (confirm==JOptionPane.YES_OPTION){
                //...
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a nurse to delete.");
        }
    }//GEN-LAST:event_NurseDeleteButtonActionPerformed

    private void PatientSearchFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PatientSearchFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientSearchFieldInputMethodTextChanged

    private void ViewInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInfoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewInfoButtonActionPerformed

    private void NurseCategorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseCategorySelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NurseCategorySelectorActionPerformed

    private void PatientCategorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientCategorySelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientCategorySelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ActionsPane;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton NurseAddButton;
    private javax.swing.JComboBox NurseCategorySelector;
    private javax.swing.JButton NurseDeleteButton;
    private javax.swing.JList NurseList;
    private javax.swing.JPanel NursePane;
    private javax.swing.JScrollPane NurseScrollList;
    private javax.swing.JTextField NurseSearchField;
    private javax.swing.JComboBox PatientCategorySelector;
    private javax.swing.JList PatientList;
    private javax.swing.JPanel PatientPane;
    private javax.swing.JScrollPane PatientScrollList;
    private javax.swing.JTextField PatientSearchField;
    private javax.swing.JLabel SignedInAsNotifier;
    private javax.swing.JButton ViewInfoButton;
    // End of variables declaration//GEN-END:variables
}
