/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Scott
 */

import java.sql.*;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

public class PatientRegister extends javax.swing.JFrame 
{
    /**
     * Creates new form PatientRegister
     */
    private NurseView parent=null;
    private ArrayList<UserInfo> names;
    
    public PatientRegister(NurseView _parent) {
        initComponents();
        buttonGroup1.add(m);
        buttonGroup1.add(f);
        userID.setText("");
        password.setText("");
        confirmPassword.setText("");
        email.setText("");
        insuranceName.setSelectedItem(-1);
        name.setText("");
        DOB.setText("");
        socSec.setText("XXXXXXXXX");
        relationTo.setText("");
        policyNum.setText("");
        groupNum.setText("");
        effDate.setText("");
        fName.setText("");
        lName.setText("");
        primPhone.setText("XXXXXXXXXX");
        otherPhone.setText("XXXXXXXXXX");
        phoneNum.setText("XXXXXXXXXX");
        ePhone.setText("XXXXXXXXXX");
        zip.setText("");
        age.setText("XXX");
        persEmail.setText("");
        address.setText("");
        city.setText("");
        state.setText("");
        eName.setText("");
        eRelation.setText("");
        parent=_parent;
        ResultSet rs;
        names = new ArrayList();
        ArrayList<String> displayNames = new ArrayList();
        try
        {
           rs = new DoctorDB("").getFromAllAccounts("firstname, lastname, username");
           while(rs.next())
           {
               String first = rs.getString("firstname");
               String last = rs.getString("lastname");
               String user = rs.getString("username");
               names.add(new UserInfo(first,last,user));
               displayNames.add(first+" "+last);
           }
           docList.setModel(new javax.swing.DefaultComboBoxModel(displayNames.toArray()));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to establish SQL connection. Please check your network settings.\nDetails: "+e.getMessage());
            e.printStackTrace();
             this.dispose();
             return;
        }
        
    }
    public PatientRegister()
    {
        this((NurseView)null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        userID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateBirth = new javax.swing.JFormattedTextField();
        zip = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        age = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        insuranceName = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        primPhone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        otherPhone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        persEmail = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        eName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        eRelation = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ePhone = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        otherName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        DOB = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        policyNum = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        groupNum = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        effDate = new javax.swing.JFormattedTextField();
        marraige = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        socSec = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        relationTo = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        phoneNum = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        docList = new javax.swing.JComboBox();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(615, 630));
        setResizable(false);

        jLabel3.setText("Enter desired account name:");

        userID.setText("drstrangelove");

        jLabel4.setText("Enter desired password:");

        jLabel5.setText("Confirm password:");

        jLabel6.setText("Enter your email for password recovery:");

        email.setText("example@example.net");

        jLabel7.setText("Doctor:");

        register.setText("Register Account");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel8.setText("For assistance, call 123-456-7890 or email administrator@healthworks.net");

        confirmPassword.setText("jPasswordField1");

        password.setText("jPasswordField2");

        jLabel10.setText("First Name:");

        jLabel11.setText("Last Name: ");

        lName.setText("Gonzalez");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("New Patient Information");

        jLabel1.setText("Address:");

        address.setText("200 S Ash Ave");

        jLabel2.setText("City:");

        city.setText("Phoenix");
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });

        jLabel9.setText("State:");

        state.setColumns(2);
        state.setText("AZ");

        jLabel13.setText("Zip:");

        jLabel14.setText("Date Of Birth:");

        dateBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        dateBirth.setText("MM/DD/YYYY");

        zip.setColumns(5);
        zip.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00000"))));
        zip.setText("85011");
        zip.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel15.setText("Gender:");

        jLabel16.setText("Age:");

        age.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        age.setText("29");

        jLabel17.setText("Insurance:");

        insuranceName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aetna", "IHC", "Humana", "Assurant", "Kaisser", "UnitedHealthOne", "Other" }));
        insuranceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceNameActionPerformed(evt);
            }
        });

        jLabel18.setText("Phone (Primary)");

        primPhone.setText("4805555555");

        jLabel19.setText("Other");

        otherPhone.setText("4804445555");

        jLabel20.setText("email:");

        persEmail.setText("emaple@example.net");

        fName.setText("Luis");

        jLabel21.setText("Emergency Contact:");

        eName.setText("Mark Gonzalez");

        jLabel22.setText("Relation:");

        eRelation.setText("Brother");

        jLabel23.setText("Phone:");

        ePhone.setText("4805665556");

        jLabel24.setText("Maratial Status:");

        jLabel25.setText("If Other, Name:");

        otherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNameActionPerformed(evt);
            }
        });

        jLabel26.setText("Insured's Name:");

        name.setText("Luiz Gonzalez");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        DOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        DOB.setText("3/5/1983");

        jLabel27.setText("Insured's Date of Birth:");

        jLabel28.setText("ID/Policy Number:");

        policyNum.setText("15038322");

        jLabel29.setText("Group Number:");

        groupNum.setText("23428");

        jLabel30.setText("Effective Date:");

        effDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        effDate.setText("6/8/2012");

        marraige.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Single", "Married", "Widowed", "Separated", "Divorced" }));

        jLabel31.setText("Insured's Social Security:");

        socSec.setText("123-45-6789");

        jLabel32.setText("Relation:");

        relationTo.setText("Self");

        jLabel33.setText("Phone:");

        phoneNum.setText("4805555555");
        phoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel34.setText("Register");

        docList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Doctor", "Dr. Rachna Singh", "Dr. Joe Smith", "Dr. Robert House" }));
        docList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docListActionPerformed(evt);
            }
        });

        m.setText("M");

        f.setText("F");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(policyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupNum, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(insuranceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25)
                                        .addGap(9, 9, 9)
                                        .addComponent(otherName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel27))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(socSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(relationTo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel33)
                                                .addGap(5, 5, 5)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(effDate)
                                                .addComponent(DOB)))))
                                .addGap(129, 129, 129)))
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(persEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(4, 4, 4)
                                        .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(primPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(m)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(eRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(f)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marraige, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2))
                        .addGap(208, 208, 208))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(docList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(primPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(otherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20)
                    .addComponent(persEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(marraige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m)
                    .addComponent(f))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(eName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(eRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(ePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(insuranceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(otherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(socSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(relationTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(policyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(groupNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(effDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel34)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(docList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
       try
       {
        //final String HOST = "jdbc:derby://localhost:1527/information";
        //String uName = "healthworks";
        //String password = "healthworks";
        //Connection con = DriverManager.getConnection(HOST,uName,password);
        //Statement stmt = con.createStatement();
        
        long pPhone,oPhone,emPhone,phoneNumber; int Zip,Age;
        boolean flag = false;
        String id = userID.getText();
        String pass = this.password.getText();
        String passConfirm = confirmPassword.getText();
        String emailID = email.getText();
        String insurance = (String)insuranceName.getSelectedItem();
        String insuredName = name.getText();
        String dateOfBirth = DOB.getText();
        String socSecNum = socSec.getText();
        String relation = relationTo.getText();
        String policyNumber = policyNum.getText();
        String groupNumber = groupNum.getText();
        String effectiveDate = effDate.getText();
        String first = fName.getText();
        String last = lName.getText();
        try
        {
            pPhone = Long.parseLong(primPhone.getText());
            oPhone = Long.parseLong(otherPhone.getText());
            phoneNumber = Long.parseLong(phoneNum.getText());
            emPhone = Long.parseLong(ePhone.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(PatientRegister.this, "Enter a valid phone number");
            return;
        }
        try
        {
            Age = Integer.parseInt(age.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(PatientRegister.this, "Enter a valid age");
            return;
        }
        try
        {
            Zip = Integer.parseInt(zip.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(PatientRegister.this, "Enter a valid zip code");
            return;
        }
        String pEmail = persEmail.getText();
        String add = address.getText();
        String City = city.getText();
        String State = state.getText();
        String emName = eName.getText();
        String emRelation = eRelation.getText();

        //String sql = "SELECT * FROM Patients";
        //ResultSet rs = stmt.executeQuery(sql);
        
        //checks if user id is taken or not
        //while(rs.next())
        //{
         //   String dbID = rs.getString("USERNAME");
           // if(dbID.equals(id))
            //{
            //    flag = true;
            //    break;
           // }
       // }
        PatientDB newPatient= new PatientDB(id);
        if (newPatient.accountExists())
        {
            JOptionPane.showMessageDialog(PatientRegister.this, "The username "+id+" has already been taken.");
            return;
        }
        //validating all entries
        if(socSec.getText().length() != 9 )
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a valid 9 digit Social Security number");
        else if(insuranceName.getSelectedItem().equals("Other"))
        {
            if(otherName.getText().equals(""))
            {
                JOptionPane.showMessageDialog(PatientRegister.this, "Please enter an Insurance Name");
            }
            insurance = otherName.getText();
        }
        else if(marraige.getSelectedItem().equals(" "))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please select a Maratial Status");
        else if(first.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a First Name");
        else if(last.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Last Name");
        else if(primPhone.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Primary Phone");
        else if(pEmail.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter an email");
        else if(add.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter your address");
        else if(City.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter your city");
        else if(State.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a state");
        else if(age.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter your age");
        else if(zip.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter your area code");
        else if(dateBirth.getText().equals("MM/DD/YYYY"))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter your date of birth");
        else if(eName.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter an emergency contact");
        else if(ePhone.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a phone number for the emergency contact");
        else if(eRelation.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "How are you related to your emergency contact?");
        else if(insuredName.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Name for the Insured Patient");
        else if(dateOfBirth.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Date of Birth");
        else if(relation.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a your Relation to the patient");
        else if(phoneNum.getText().equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Phone Number");
        else if(policyNumber.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Policy Number");
        else if(groupNumber.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a Group Number");
        else if(effectiveDate.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter the effective date of your insurance");
        else if(id.equals(""))//error message shown if id field blank
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter a User ID");
        else if(flag)//error if id in use
            JOptionPane.showMessageDialog(PatientRegister.this, "ID already in use");
        else if(emailID.equals(""))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please enter an email address to recover your account");
        else if(!(pass.equals(passConfirm)))
            JOptionPane.showMessageDialog(PatientRegister.this, "Passwords do not match");
        else if(docList.getSelectedItem().equals("Select Doctor"))
            JOptionPane.showMessageDialog(PatientRegister.this, "Please select a doctor");
        else if(buttonGroup1.getSelection() == null)
            JOptionPane.showMessageDialog(PatientRegister.this, "Please select your gender");
        else
        {  
                String doc = names.get(docList.getSelectedIndex()).username;
                String status = (String)(marraige.getSelectedItem());
                String gender;
                if(m.isSelected()) {
                        gender = "0";
                    }
                else {
                       gender = "1";
                    }
          
                newPatient.createAccount(first,last,pass,emailID);
                newPatient.createTable();
                newPatient.setDoctor(doc);
                newPatient.setEmergencyInfo(emName, ePhone.getText(), emRelation);
                newPatient.setPersonalInfo(first,last,primPhone.getText(),otherPhone.getText(),gender,status,age.getText(),dateBirth.getText(),pEmail);
                newPatient.setInsuranceInfo(insurance, insuredName, dateOfBirth,socSec.getText(),relation,phoneNum.getText(),policyNumber,groupNumber,effectiveDate);
                newPatient.setAddress(add, City, State, zip.getText());

                if (parent!=null) {
                    parent.PatientAddedByRegisterForm(new UserInfo(first,last,id));
                }
                JOptionPane.showMessageDialog(this,"Registration successful!");
                dispose();
        }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(this,"Unable to establish SQL connection. Please check your network settings.\nDetails: "+e.getMessage());
           e.printStackTrace();
        this.dispose();
        return;
       
        }    }//GEN-LAST:event_registerActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void insuranceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceNameActionPerformed

    private void otherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherNameActionPerformed

    private void phoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumActionPerformed

    private void docListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new PatientRegister().setVisible(true);
            }
        });
        
        
             
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JFormattedTextField DOB;
    private static javax.swing.JTextField address;
    private static javax.swing.JFormattedTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private static javax.swing.JTextField city;
    private static javax.swing.JPasswordField confirmPassword;
    private static javax.swing.JFormattedTextField dateBirth;
    private static javax.swing.JComboBox docList;
    private static javax.swing.JTextField eName;
    private static javax.swing.JTextField ePhone;
    private static javax.swing.JTextField eRelation;
    private static javax.swing.JFormattedTextField effDate;
    private static javax.swing.JTextField email;
    private static javax.swing.JRadioButton f;
    private static javax.swing.JTextField fName;
    private static javax.swing.JTextField groupNum;
    private static javax.swing.JComboBox insuranceName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private static javax.swing.JTextField lName;
    private static javax.swing.JRadioButton m;
    private static javax.swing.JComboBox marraige;
    private static javax.swing.JTextField name;
    private static javax.swing.JTextField otherName;
    private static javax.swing.JTextField otherPhone;
    private static javax.swing.JPasswordField password;
    private static javax.swing.JTextField persEmail;
    private static javax.swing.JTextField phoneNum;
    private static javax.swing.JTextField policyNum;
    private static javax.swing.JTextField primPhone;
    private javax.swing.JButton register;
    private static javax.swing.JTextField relationTo;
    private static javax.swing.JTextField socSec;
    private static javax.swing.JTextField state;
    private static javax.swing.JTextField userID;
    private static javax.swing.JFormattedTextField zip;
    // End of variables declaration//GEN-END:variables
}
