/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Scott
 */

import java.sql.*;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

public class PatientEditInfo extends javax.swing.JFrame 
{
    private String user;
    private PatientDB p;;
    
    public PatientEditInfo(String username) {
        initComponents();
        user = username;
        
        p = new PatientDB(user);
        try
        {
            buttonGroup1.add(m);
            buttonGroup1.add(f);
            
            if(p.queryField("gender").equals("0"))
                m.setSelected(true);
            else
               f.setSelected(true);
            
            String stat = p.queryField("status");
            if(stat.equals("Single"))
                marraige.setSelectedIndex(0);
            else if(stat.equals("Married"))
                marraige.setSelectedIndex(1);
            else if(stat.equals("Divorced"))
                marraige.setSelectedIndex(4);
            else if(stat.equals("Separated"))
                marraige.setSelectedIndex(3);
            else if(stat.equals("Widowed"))
                marraige.setSelectedIndex(2);
            
            String ins = p.queryField("insurance");
            if(ins.equals("Aetna"))
                insuranceName.setSelectedIndex(0);
            else if(ins.equals("IHC"))
                insuranceName.setSelectedIndex(1);
            else if(ins.equals("Humana"))
                insuranceName.setSelectedIndex(2);
            else if(ins.equals("Assurant"))
                insuranceName.setSelectedIndex(3);
            else if(ins.equals("Kaisser"))
                insuranceName.setSelectedIndex(4);
            else if(ins.equals("UnitedHealthOne"))
                insuranceName.setSelectedIndex(5);
            else
            {
                insuranceName.setSelectedIndex(6);
                otherName.setText(ins);
            }
            
            
            name.setText(p.queryField("insuredname"));
            DOB.setText(p.queryField("dateofbirth"));
            socSec.setText(p.queryField("socsec"));
            relationTo.setText(p.queryField("relation"));
            policyNum.setText(p.queryField("policynum"));
            groupNum.setText(p.queryField("groupnum"));
            effDate.setText(p.queryField("effdate"));
            fName.setText(p.queryField("firstname"));
            lName.setText(p.queryField("lastname"));
            primPhone.setText(p.queryField("primephone"));
            otherPhone.setText(p.queryField("otherphone"));
            phoneNum.setText(p.queryField("phonenum"));
            ePhone.setText(p.queryField("emergencyph"));
            zip.setText(p.queryField("zip"));
            age.setText(p.queryField("age"));
            persEmail.setText(p.queryField("personalemail"));
            address.setText(p.queryField("address"));
            city.setText(p.queryField("city"));
            state.setText(p.queryField("state"));
            eName.setText(p.queryField("emergencyname"));
            eRelation.setText(p.queryField("emergencyrel"));
            dateBirth.setText(p.queryField("dob"));
        }
        catch(SQLException e)
       {
            JOptionPane.showMessageDialog(this,"Unable to establish SQL connection. Please check your network settings.\nDetails: "+e.getMessage());
            e.printStackTrace();
       }
    }
    public PatientEditInfo()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        edit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateBirth = new javax.swing.JFormattedTextField();
        zip = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        age = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        insuranceName = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        primPhone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        otherPhone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        persEmail = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        eName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        eRelation = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ePhone = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        otherName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        DOB = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        policyNum = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        groupNum = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        effDate = new javax.swing.JFormattedTextField();
        marraige = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        socSec = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        relationTo = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        phoneNum = new javax.swing.JTextField();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(615, 430));
        setMinimumSize(new java.awt.Dimension(615, 430));
        setPreferredSize(new java.awt.Dimension(615, 430));
        setResizable(false);

        edit.setText("Update Account");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel8.setText("For assistance, call 123-456-7890 or email administrator@healthworks.net");

        jLabel10.setText("First Name:");

        jLabel11.setText("Last Name: ");

        lName.setText("Gonzalez");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Edit Patient Information");

        jLabel1.setText("Address:");

        address.setText("200 S Ash Ave");

        jLabel2.setText("City:");

        city.setText("Phoenix");

        jLabel9.setText("State:");

        state.setColumns(2);
        state.setText("AZ");

        jLabel13.setText("Zip:");

        jLabel14.setText("Date Of Birth:");

        dateBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        dateBirth.setText("MM/DD/YYYY");

        zip.setColumns(5);
        zip.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00000"))));
        zip.setText("85011");
        zip.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel15.setText("Gender:");

        jLabel16.setText("Age:");

        age.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        age.setText("29");

        jLabel17.setText("Insurance:");

        insuranceName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aetna", "IHC", "Humana", "Assurant", "Kaisser", "UnitedHealthOne", "Other" }));
        insuranceName.setSelectedIndex(-1);

        jLabel18.setText("Phone (Primary)");

        primPhone.setText("4805555555");

        jLabel19.setText("Other");

        otherPhone.setText("4804445555");

        jLabel20.setText("email:");

        persEmail.setText("emaple@example.net");

        fName.setText("Luis");

        jLabel21.setText("Emergency Contact:");

        eName.setText("Mark Gonzalez");

        jLabel22.setText("Relation:");

        eRelation.setText("Brother");

        jLabel23.setText("Phone:");

        ePhone.setText("4805665556");

        jLabel24.setText("Maratial Status:");

        jLabel25.setText("If Other, Name:");

        jLabel26.setText("Insured's Name:");

        name.setText("Luiz Gonzalez");

        DOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        DOB.setText("3/5/1983");

        jLabel27.setText("Insured's Date of Birth:");

        jLabel28.setText("ID/Policy Number:");

        policyNum.setText("15038322");

        jLabel29.setText("Group Number:");

        groupNum.setText("23428");

        jLabel30.setText("Effective Date:");

        effDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        effDate.setText("6/8/2012");

        marraige.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Widowed", "Separated", "Divorced" }));
        marraige.setSelectedIndex(-1);

        jLabel31.setText("Insured's Social Security:");

        socSec.setText("123-45-6789");

        jLabel32.setText("Relation:");

        relationTo.setText("Self");

        jLabel33.setText("Phone:");

        phoneNum.setText("4805555555");

        m.setText("M");

        f.setText("F");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(socSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(relationTo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel33)
                                        .addGap(5, 5, 5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(effDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DOB)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(policyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupNum, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(4, 4, 4)
                                        .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(primPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(eRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(m)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(f)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel24)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(marraige, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(insuranceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otherName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(308, 308, 308)
                                    .addComponent(persEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(primPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(otherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20)
                    .addComponent(persEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(marraige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m)
                    .addComponent(f))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(eName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(eRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(ePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(insuranceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(otherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(socSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(relationTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(policyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(groupNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(effDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       try
       {
        long pPhone,oPhone,emPhone,phoneNumber; int Zip,Age;
        boolean flag = false;
        String insurance = (String)insuranceName.getSelectedItem();
        String insuredName = name.getText();
        String dateOfBirth = DOB.getText();
        String socSecNum = socSec.getText();
        String relation = relationTo.getText();
        String policyNumber = policyNum.getText();
        String groupNumber = groupNum.getText();
        String effectiveDate = effDate.getText();
        String first = fName.getText();
        String last = lName.getText();
        try
        {
            pPhone = Long.parseLong(primPhone.getText());
            oPhone = Long.parseLong(otherPhone.getText());
            phoneNumber = Long.parseLong(phoneNum.getText());
            emPhone = Long.parseLong(ePhone.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Enter a valid phone number");
            return;
        }
        try
        {
            Age = Integer.parseInt(age.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Enter a valid age");
            return;
        }
        try
        {
            Zip = Integer.parseInt(zip.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Enter a valid zip code");
            return;
        }
        String pEmail = persEmail.getText();
        String add = address.getText();
        String City = city.getText();
        String State = state.getText();
        String emName = eName.getText();
        String emRelation = eRelation.getText();

        //validating all entries
        if(socSec.getText().length() != 9 )
            JOptionPane.showMessageDialog(this, "Please enter a valid 9 digit Social Security number");
        else if(insuranceName.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this, "Please enter an Insurance Name");
        else if(insuranceName.getSelectedItem().equals("Other"))
        {
            if(otherName.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter an Insurance Name");
            }
            insurance = otherName.getText();
        }
        else if(marraige.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this, "Please select a Maratial Status");
        else if(first.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a First Name");
        else if(last.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a Last Name");
        else if(primPhone.getText().equals("") || primPhone.getText().equals("XXXXXXXXXX"))
            JOptionPane.showMessageDialog(this, "Please enter a Primary Phone");
        else if(pEmail.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter an email");
        else if(add.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter your address");
        else if(City.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter your city");
        else if(State.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a state");
        else if(age.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Please enter your age");
        else if(zip.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Please enter your area code");
        else if(dateBirth.getText().equals("MM/DD/YYYY"))
            JOptionPane.showMessageDialog(this, "Please enter your date of birth");
        else if(eName.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Please enter an emergency contact");
        else if(ePhone.getText().equals("") || ePhone.getText().equals("XXXXXXXXXX"))
            JOptionPane.showMessageDialog(this, "Please enter a phone number for the emergency contact");
        else if(eRelation.getText().equals(""))
            JOptionPane.showMessageDialog(this, "How are you related to your emergency contact?");
        else if(insuredName.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a Name for the Insured Patient");
        else if(dateOfBirth.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a Date of Birth");
        else if(relation.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a your Relation to the patient");
        else if(phoneNum.getText().equals("") || phoneNum.getText().equals("XXXXXXXXXX"))
            JOptionPane.showMessageDialog(this, "Please enter a Phone Number");
        else if(policyNumber.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a Policy Number");
        else if(groupNumber.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter a Group Number");
        else if(effectiveDate.equals(""))
            JOptionPane.showMessageDialog(this, "Please enter the effective date of your insurance");
        else if(buttonGroup1.getSelection() == null)
            JOptionPane.showMessageDialog(this, "Please select your gender");
        else
        {  
                String status = (String)(marraige.getSelectedItem());
                String gender;
                if(m.isSelected()) 
                {
                    gender = "0";
                }
                else 
                {
                    gender = "1";
                }
          
                p.setEmergencyInfo(emName, ePhone.getText(), emRelation);
                p.setPersonalInfo(first,last,primPhone.getText(),otherPhone.getText(),gender,status,age.getText(),dateBirth.getText(),pEmail);
                p.setInsuranceInfo(insurance, insuredName, dateOfBirth,socSec.getText(),relation,phoneNum.getText(),policyNumber,groupNumber,effectiveDate);
                p.setAddress(add, City, State, zip.getText());

                JOptionPane.showMessageDialog(this,"Update Successful!");
                dispose();
        }
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(this,"Unable to establish SQL connection. Please check your network settings.\nDetails: "+e.getMessage());
           e.printStackTrace();
        this.dispose();
        return;
       
        }    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new PatientRegister().setVisible(true);
            }
        });
        
        
             
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JFormattedTextField DOB;
    private static javax.swing.JTextField address;
    private static javax.swing.JFormattedTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private static javax.swing.JTextField city;
    private static javax.swing.JFormattedTextField dateBirth;
    private static javax.swing.JTextField eName;
    private static javax.swing.JTextField ePhone;
    private static javax.swing.JTextField eRelation;
    private javax.swing.JButton edit;
    private static javax.swing.JFormattedTextField effDate;
    private static javax.swing.JRadioButton f;
    private static javax.swing.JTextField fName;
    private static javax.swing.JTextField groupNum;
    private static javax.swing.JComboBox insuranceName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTextField lName;
    private static javax.swing.JRadioButton m;
    private static javax.swing.JComboBox marraige;
    private static javax.swing.JTextField name;
    private static javax.swing.JTextField otherName;
    private static javax.swing.JTextField otherPhone;
    private static javax.swing.JTextField persEmail;
    private static javax.swing.JTextField phoneNum;
    private static javax.swing.JTextField policyNum;
    private static javax.swing.JTextField primPhone;
    private static javax.swing.JTextField relationTo;
    private static javax.swing.JTextField socSec;
    private static javax.swing.JTextField state;
    private static javax.swing.JFormattedTextField zip;
    // End of variables declaration//GEN-END:variables
}
